### ISSUE TITLE
Ensure every <image> has an xml:id

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/calculus#78] opened 2023-09-20 13:34 UTC
Incorrect graph showing for [Activity 2.5.6](https://teambasedinquirylearning.github.io/calculus/2023/DF5.html#chain-rule-practice-graphs). The question references two functions. 

Here's what it was in the 2022 edition: [Activity 2.5.9](https://teambasedinquirylearning.github.io/calculus/2022/DF5.html#chain-rule-practice-graphs)

**Comment by siwelwerd** [comment] 2023-09-25 20:48
I think @StevenClontz should take a look at this one. The tikz code that *should* produce the correct image is at

https://github.com/TeamBasedInquiryLearning/calculus/blob/a7bcf7339e32bf824512fd1019864f747c93f0d2/source/02-DF/05.ptx#L127

However, I don't understand why a different generated image is being included.

**Comment by StevenClontz** [comment] 2023-09-25 20:54
While it should be working without one, the lack of an xml:id on the image is the root of many generated asset errors, and adding one will likely fix the problem.

**Comment by StevenClontz** [comment] 2023-09-25 20:59
Here's what I mean:

https://github.com/TeamBasedInquiryLearning/calculus/pull/89

But rather than merging that in (which I haven't built with PreTeXt to double-check my solution works), I should audit the whole book to ensure every `<image>` has an xml:id. A semantically-meaningful ID is best, but a random unique ID is still better than nothing (and could be added programmatically).

**Comment by siwelwerd** [comment] 2023-09-25 21:02
Audit results:

```
(base) drew@Drews-MacBook-Pro calculus % grep -n \<image\> source/*/*.ptx
source/01-LT/05.ptx:95:                    <image>
source/01-LT/05.ptx:115:                    <image>
source/01-LT/05.ptx:134:                    <image>
source/01-LT/05.ptx:156:                    <image>
source/01-LT/05.ptx:176:                    <image>
source/01-LT/05.ptx:196:                    <image>
source/02-DF/05.ptx:125:                    <image>
source/02-DF/08.ptx:83:                    <image>
source/02-DF/08.ptx:199:                    <image>
source/02-DF/08.ptx:309:                    <image>
```

**Comment by siwelwerd** [comment] 2023-09-25 21:11
Ah, that didn't catch things like

https://github.com/TeamBasedInquiryLearning/calculus/blob/a7bcf7339e32bf824512fd1019864f747c93f0d2/source/03-AD/04.ptx#L29C21-L29C40

Which is the root cause of #77

**Comment by siwelwerd** [comment] 2023-09-25 21:14
Here is a more complete listing
```
(base) drew@Drews-MacBook-Pro calculus % grep -n image source/*/*.ptx | grep -v xml:id | grep -v latex-image | grep -v /image
source/01-LT/01.ptx:20:                <image width="50%" source="limit_censored.png" />
source/01-LT/01.ptx:56:                <image width="50%" source="limit_uncensored.png" />
source/01-LT/01.ptx:133:                <image width="50%" source="limit-left-and-right.png" />
source/01-LT/01.ptx:208:                <image width="50%" source="limits-one-sided-fluency.png" />
source/01-LT/01.ptx:296:                <image width="100%" source="squeeze.png" />
source/01-LT/02.ptx:266:       <image width="50%" source="limits_numerical5_graph.png" />
source/01-LT/03.ptx:205:                <image width="50%">
source/01-LT/03.ptx:245:                <image width="50%">
source/01-LT/04.ptx:63:          <image source="limits-different-kinds.png" width="50%">
source/01-LT/04.ptx:157:          <image source="limits-different-kinds.png" width="50%">
source/01-LT/04.ptx:240:                <image width="50%">
source/01-LT/05.ptx:95:                    <image>
source/01-LT/05.ptx:115:                    <image>
source/01-LT/05.ptx:134:                    <image>
source/01-LT/05.ptx:156:                    <image>
source/01-LT/05.ptx:176:                    <image>
source/01-LT/05.ptx:196:                    <image>
source/01-LT/05.ptx:342:                <image width="50%">
source/01-LT/05.ptx:399:                    <image width="50%">
source/01-LT/06.ptx:22:                <image width="50%">
source/01-LT/06.ptx:231:                    <image width="50%">
source/02-DF/01.ptx:133:                    <image width="50%">
source/02-DF/01.ptx:278:                    <image width="50%">
source/02-DF/01.ptx:335:                    <image width="50%">
source/02-DF/01.ptx:449:                    <image width="50%">
source/02-DF/07.ptx:69:       <image width="70%" source="derivative_implicit2_graph.png" />
source/02-DF/07.ptx:85:       <image width="70%" source="derivative_implicit3_graph.png" />
source/02-DF/07.ptx:130:       <image width="50%" source="coop.jpg" />
source/02-DF/08.ptx:83:                    <image>
source/02-DF/08.ptx:199:                    <image>
source/02-DF/08.ptx:309:                    <image>
source/03-AD/02.ptx:54:                    <image width="50%">
source/03-AD/04.ptx:29:                    <image width="50%">
source/03-AD/04.ptx:105:       <image width="25%" source="evt_int.png" />
source/03-AD/04.ptx:110:       <image width="25%" source="evt_endpts.png" />
source/03-AD/04.ptx:114:       <image width="25%" source="evt_mixed.png" />
source/03-AD/04.ptx:119:       <image width="25%" source="evt_mixed2.png" />
source/03-AD/06.ptx:31:      <image width="100%" source="concavity-1" />
source/03-AD/06.ptx:96:      <image width="100%" source="concavity-2" />
source/03-AD/06.ptx:155:      <image width="90%" source="concavity-3" />
source/03-AD/07.ptx:25:      <image width="30%" source="dec-cdown.png" />
source/03-AD/07.ptx:49:      <image width="30%" source="inc-cdown.png" />
source/03-AD/08.ptx:121:          Label these quantities appropriately on the image shown in <xref ref="F-3-4-PA1">Figure</xref>.
source/03-AD/08.ptx:126:          <image width="47%" source="3_4_PA1" />
source/04-IN/01.ptx:113:       <image width="100%" source="fig2d.JPG" />
source/04-IN/02.ptx:34:          <image width="100%" source="4_1_PA1" />
source/04-IN/02.ptx:133:        <image source="4_1_Act1" />
source/04-IN/05.ptx:21:          <image width="50%" source="area1.png" />
source/04-IN/05.ptx:30:          <image width="50%" source="riemann1.png" />
source/04-IN/05.ptx:99:          <image width="50%" source="x2plus3.png" />
source/04-IN/05.ptx:106:          <image width="50%" source="sqrtx.png" />
source/04-IN/05.ptx:113:          <image width="50%" source="cosx.png" />
source/04-IN/05.ptx:127:          <image width="50%" source="linedefint.png" />
source/04-IN/05.ptx:137:          <image width="50%" source="exminus2.png" />
source/04-IN/05.ptx:149:          <image width="50%" source="defintarea1.png" />
source/04-IN/05.ptx:155:          <image width="50%" source="defintarea2.png" />
source/04-IN/08.ptx:64:    <image width="55%" source="area_between.png" />
source/07-CO/05.ptx:71:                <image width="100%">
source/07-CO/05.ptx:132:                <image width="100%">
source/07-CO/06.ptx:142:                <image width="100%">
source/07-CO/06.ptx:203:                <image width="100%">
```

My guess is that with the source included we are not seeing the errors, but perhaps all of them need a semantic xml:id anyways

**Comment by siwelwerd** [comment] 2023-09-25 21:20
Though, this might be an upstream issue as well: If PreTeXt is going to require an xml:id in an `<image>` to behave appropriately, it should enforce that during the build.

Also, this might be a severe enough issue to warrant fixing in the currently published version.  Before I get started on this, would that affect the workflow for correcting these?

**Comment by StevenClontz** [comment] 2023-09-26 18:28
It's less "PreTeXt requires an xml:id" than "PreTeXt is harder to use incorrectly when xml:ids are used". And by "use" here I mean both by authors, and by the PreTeXt-CLI authoring tools where the bug may exist.

**Comment by StevenClontz** [comment] 2023-09-26 18:31
I think we're discussing this in an hour, but I agree that we should fix the live version of the book. I have a hunch on how to do this that isn't too disruptive, so I'm going to take a stab now.

**Comment by StevenClontz** [comment] 2023-09-26 18:50
(My hunch was wrong, but still working on this...)

**Comment by siwelwerd** [comment] 2023-09-26 18:53
I'm happy to put time into this, but want to make sure I do so in a way that makes it easier to update the live version of the book.  Though I don't think any major changes have been done since publication, so just pushing the 2024 down to the live version (once this is fixed) might be a workable solution.

**Comment by siwelwerd** [comment] 2023-09-26 18:54
Re a possible issue with the CLI: I wonder if this is related.

https://github.com/PreTeXtBook/pretext-cli/issues/579

**Comment by StevenClontz** [comment] 2023-09-26 19:18
I mean, one solution which isn't exciting: put xml:ids on everything in live version, so the 2024 preview looks good. Then manually rename them from `xmlid.svg` to `image-123.svg` to work with the 2023 edition. 

One other thing I might try: figure out how to use the core PreTeXt script to generate assets rather than the CLI. If those are correct, we can fix the 2023 edition that way.

**Comment by siwelwerd** [comment] 2023-09-26 19:58
@AbbyANoble : We think we have a quick fix pushed out.  Can you double check here https://teambasedinquirylearning.github.io/calculus/2023/DF5.html that the original issue you pointed out is fixed, as well as #77 ?

**Comment by AbbyANoble** [comment] 2023-09-26 20:01
@siwelwerd  - Those look good now!

**Comment by StevenClontz** [comment] 2023-09-26 22:18
Sweet. Leaving this open until we've left no image xml:id behind, and to remind me to contribute to PreTeXt ecosystem so this won't be an issue for anyone else.

**Comment by StevenClontz** [comment] 2023-09-27 13:25
Closing this but assigning myself to https://github.com/PreTeXtBook/pretext-cli/issues/579 for future.

**Closed by StevenClontz** 2023-09-27 13:25 UTC
